Uncaught TypeError: authService.isAuthenticated is not a function fixed it by renaming since thers a state variabe named the same renamed it to checkIsAuthenticated